# Generated by Django 3.2.2 on 2021-05-07 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210507_1941'),
        ('attractions', '0002_auto_20210507_1941'),
        ('rating', '0002_auto_20210507_1941'),
        ('address', '0002_auto_20210507_1941'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('attractions', models.ManyToManyField(default=None, to='attractions.Attractions')),
                ('rate', models.ManyToManyField(default=None, to='rating.Rating')),
                ('reviews', models.ManyToManyField(default=None, to='reviews.Reviews')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
