# Generated by Django 3.2.2 on 2021-05-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20210507_1941'),
        ('points', '0002_auto_20210507_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
